---

- name: Install Netdata repo key.
  ansible.builtin.apt_key:
    url: "{{ netdata_key_uri }}"
    state: present

- name: Add Netdata repository
  ansible.builtin.apt_repository:
    repo: "{{ netdata_repo_uri }}"
    state: present
    filename: 'netdata'
    update_cache: yes
